[build]
builder = "nixpacks"

[nixpacks]
setup = ["python311", "gcc", "ffmpeg"]
install = ["python -m pip install --upgrade pip", "pip install -r requirements.txt"]
start = "python src/api.py"

[deploy]
startCommand = "python src/api.py"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 