[build]
builder = "nixpacks"
buildCommand = """
echo "Installing requirements..." &&
pip install -r requirements.txt &&
echo "Verifying installation:" &&
pip list
"""

[nixpacks]
setup = ["python311", "gcc", "python3-dev", "pkg-config", "ffmpeg", "portaudio19-dev", "libasound2-dev"]

[deploy]
startCommand = """
bash -c '
echo "=== Starting Application ===" &&
echo "Current directory: $(pwd)" &&
echo "Python version: $(python --version)" &&
echo "Listing current directory:" &&
ls -la &&
echo "Starting uvicorn..." &&
PORT=${PORT:-8000} &&
{
    PYTHONUNBUFFERED=1 RAILWAY_ENVIRONMENT=true uvicorn api:app --host 0.0.0.0 --port $PORT --log-level debug 2>&1 | tee -a app.log
    exit_code=$?
    if [ $exit_code -ne 0 ]; then
        echo "Application failed to start with exit code $exit_code"
        echo "Last 50 lines of app.log:"
        tail -n 50 app.log
        exit $exit_code
    fi
}
'
"""
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 