[build]
builder = "nixpacks"
buildCommand = "pip install fastapi uvicorn psutil"

[deploy]
startCommand = "bash -c 'uvicorn minimal_test:app --host 0.0.0.0 --port 8080 --workers 4 --timeout-keep-alive 75'"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3 