[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
startupTimeout = "60s"

[service]
rootDirectory = "backend"
startCommand = "uvicorn api:app --host 0.0.0.0 --port $PORT" 