[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python src/api.py"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[nixpacks]
python_version = "3.11.7"
start_phase = "python src/api.py" 