[build]
builder = "nixpacks"
buildCommand = "set -x && python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt && cp -r src/* /app/src/"

[nixpacks]
setup = ["python311", "gcc", "python3-venv", "python3-dev", "python3-pip"]

[deploy]
startCommand = "bash -c 'PYTHONPATH=/app uvicorn src.api:app --host 0.0.0.0 --port ${PORT}'"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 