[build]
builder = "nixpacks"
buildCommand = "pip install fastapi uvicorn psutil"

[deploy]
startCommand = "bash -c 'export PORT=${PORT:-8080} && uvicorn minimal_test:app --host 0.0.0.0 --port $PORT --log-level debug'"
healthcheckPath = "/_health"
healthcheckTimeout = 10
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3 