[build]
builder = "nixpacks"
buildCommand = """
set -x && 
mkdir -p /app/src && 
cp -r src/* /app/src/ && 
cp -r * /app/ && 
python -m venv --copies /opt/venv && 
. /opt/venv/bin/activate && 
pip install -r requirements.txt &&
echo "Contents of /app:" &&
ls -la /app &&
echo "Contents of /app/src:" &&
ls -la /app/src
"""

[nixpacks]
setup = ["python311", "gcc", "python3-venv", "python3-dev", "python3-pip"]

[deploy]
startCommand = """
bash -c '
echo "Starting deployment..." &&
echo "Current directory: $PWD" &&
echo "Python path: $PYTHONPATH" &&
echo "Listing /app:" &&
ls -la /app &&
echo "Listing /app/src:" &&
ls -la /app/src &&
cd /app &&
PYTHONPATH=/app PORT=${PORT:-8000} uvicorn src.api:app --host 0.0.0.0 --port ${PORT:-8000} --log-level debug
'
"""
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 