[build]
builder = "nixpacks"
buildCommand = "set -x && python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"

[nixpacks]
setup = ["python311", "gcc", "python3-venv", "python3-dev", "python3-pip"]

[deploy]
startCommand = "bash -c 'cd /app && PYTHONPATH=/app PORT=${PORT:-8000} uvicorn src.api:app --host 0.0.0.0 --port ${PORT:-8000}'"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 