[build]
builder = "nixpacks"
buildCommand = "pip install fastapi uvicorn psutil"

[deploy]
startCommand = "uvicorn minimal_test:app --host 0.0.0.0 --port 8080 --log-level debug"
healthcheckPath = "/_health"
healthcheckTimeout = 10
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3 